### ISSUE TITLE
Add patch to fix inferior calls on RISC-V

### ISSUE THREAD

**Issue by xobs** [xpack-dev-tools/riscv-none-embed-gcc-xpack#1]
This package appears to follow upstream binutils, which as of right now does not yet have a release that fixes inferior calls (i.e. the `call` command) on RISC-V.  This patch fixes the issue: https://sourceware.org/ml/gdb-patches/2019-07/msg00450.html

This was reported to riscv/riscv-binutils-gdb which pointed me to the patch list.

**Comment by ilg-ul** [comment]
Thank you for the patch, but this distribution plans to follow the SiFive distribution, and do not introduce functional differences.

After SiFive will make a new release that includes this patch please let me know, and I'll follow it.
