### ISSUE TITLE
Add non-C multi-libs

### ISSUE THREAD

**Issue by ilg-ul** [xpack-dev-tools/riscv-none-embed-gcc-xpack#12]
The SiFive release v2020.12.0 changed the list of multi-libs and did not include any non-C libraries.

As discussed in [#10], these libraries are necessary and there are a lot of designs, like gatecount/area conscious soft IP implementation targeting FPGA, that do not use the optional compressed instructions.

**Comment by ilg-ul** [comment]
The Intel Linux & Windows pre-release v10.2.0-1.2 archives are available for testing from:

- <https://github.com/xpack-dev-tools/pre-releases/releases/tag/test>

There are **a lot** of libraries, I hope that we cover most use cases. And the archives are smaller than before. :-)

Manu @manukuma-intel, could you confirm that the new binaries are functional for your projects?

---

The Arm Linux and macOS builds will take more time to complete, the public release will probably be available tomorrow.

**Comment by manukuma-intel** [comment]
That pre-release works great Liviu @ilg-ul! I tested rv32ia usage in hardware (FPGA) with the new toolchain both on x86_64 Linux and x86_64 Windows. ELFs run just fine. As well the output of `--print-multi-lib` prints a lot more libs (both compressed and non-compressed).

Nice job on the size! I was expecting we'd have to bite the bullet on the size, but looks like that debug info took quite a lot of space. Now we get more multi-libs and it's still around ~500 MB download :).

**Comment by ilg-ul** [comment]
Thank you for testing, now all binaries are ready, so I'll proceed with the release.

**Comment by ilg-ul** [comment]
Fixed on 2021-11-11 in 10.2.0-1.2.

**Comment by TommyMurphyTM1234** [comment]
> There are **a lot** of libraries, I hope that we cover most use cases. And the archives are smaller than before. :-)

Unfortunately, I don't see the general case, with even more standardised extensions (and potentially different versions!), ever being tractable with this approach but I don't have any other ideas right now... :-|

https://github.com/riscv/riscv-v-spec/issues/723

**Comment by ilg-ul** [comment]
Yeah, it looks like the RISC-V design entered a weirdness contest. :-(
