### ISSUE TITLE
Request: OSX M1 binaries

### ISSUE THREAD

**Issue by Grazfather** [xpack-dev-tools/riscv-none-embed-gcc-xpack#16]
I would love M1-max compatible binaries.

Looks like the build-helper recently added support for this, so if this is the case, then hopefully it's not a lot more work than updating the submodule and adding new targets to the workflows.

I could take a crack at it if I were approved to run workflows, but otherwise I am happy to just help test.

**Comment by ilg-ul** [comment]
Hi @Grazfather,

Yes, all other binary xPacks were updated, but unfortunately the RISC-V toolchain is too old, and GCC 10.1 cannot be compiled for Apple Silicon, the oldest patches that I could find are for 10.2. :-(

I asked SiFive for an update, but so far I did not get an answer from them.

**Comment by Grazfather** [comment]
Ah too bad! I can probably live with the x86_64 binaries for now! I just have to run things in separate steps 'cause my others tools are arm64 :)

**Comment by ilg-ul** [comment]
Well, I also plan to switch my development machine to Apple Silicon, and my workflow is based on binary xPacks, so running the x86_64 binaries is not an option; thus I'll have to figure out a solution.

If SiFive will not make their sources public, we might have to use the official GNU GCC repository, but I don't know how well this will work, some functionality might not have been upstreamed. :-(

Do you have any experience with other RISC-V toolchains?

**Comment by Grazfather** [comment]
Unfortunately not. I am just dipping my toe into riscv stuff and this xpack made it so that luckily I did not need to explore a lot.

**Comment by ilg-ul** [comment]
Ok, I'll let you know when I find a solution.

**Comment by ilg-ul** [comment]
This project is marked as DEPRECATED and is no longer maintained.

Please use the new project, riscv-none-elf-gcc-xpack, which already provides binaries for Apple silicon machines.
