### ISSUE TITLE
undefined reference to _exit

### ISSUE THREAD

**Issue by puxiancheng** [xpack-dev-tools/riscv-none-embed-gcc-xpack#2]
Hi,
when i build a riscv hello project, 

#include <stdio.h>
int
main(void)
{
  printf("Hello RISC-V World!" "\n");
  return 0;
}

the eclipse console displays these information

16:36:18 **** Incremental Build of configuration Debug for project hello ****
make all 
Building target: hello.elf
Invoking: GNU RISC-V Cross C Linker
riscv-none-embed-gcc -msmall-data-limit=8 -mno-save-restore -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections  -g3 -Xlinker --gc-sections -Wl,-Map,"hello.map" -o "hello.elf"  ./src/main.o   
e:/program files/eclipse/xpack/risc-v embedded gcc/8.2.0-3.1/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/bin/ld.exe: e:/program files/eclipse/xpack/risc-v embedded gcc/8.2.0-3.1/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/lib/rv32imac/ilp32\libg.a(lib_a-exit.o): in function `.L0 ':
exit.c:(.text.exit+0x1e): undefined reference to `_exit'
e:/program files/eclipse/xpack/risc-v embedded gcc/8.2.0-3.1/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/bin/ld.exe: e:/program files/eclipse/xpack/risc-v embedded gcc/8.2.0-3.1/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/lib/rv32imac/ilp32\libg.a(lib_a-sbrkr.o): in function `.L0 ':
sbrkr.c:(.text._sbrk_r+0xe): undefined reference to `_sbrk'
e:/program files/eclipse/xpack/risc-v embedded gcc/8.2.0-3.1/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/bin/ld.exe: e:/program files/eclipse/xpack/risc-v embedded gcc/8.2.0-3.1/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/lib/rv32imac/ilp32\libg.a(lib_a-writer.o): in function `.L0 ':
writer.c:(.text._write_r+0x14): undefined reference to `_write'
e:/program files/eclipse/xpack/risc-v embedded gcc/8.2.0-3.1/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/bin/ld.exe: e:/program files/eclipse/xpack/risc-v embedded gcc/8.2.0-3.1/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/lib/rv32imac/ilp32\libg.a(lib_a-closer.o): in function `.L0 ':
closer.c:(.text._close_r+0xe): undefined reference to `_close'
e:/program files/eclipse/xpack/risc-v embedded gcc/8.2.0-3.1/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/bin/ld.exe: e:/program files/eclipse/xpack/risc-v embedded gcc/8.2.0-3.1/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/lib/rv32imac/ilp32\libg.a(lib_a-lseekr.o): in function `.L0 ':
lseekr.c:(.text._lseek_r+0x14): undefined reference to `_lseek'
e:/program files/eclipse/xpack/risc-v embedded gcc/8.2.0-3.1/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/bin/ld.exe: e:/program files/eclipse/xpack/risc-v embedded gcc/8.2.0-3.1/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/lib/rv32imac/ilp32\libg.a(lib_a-readr.o): in function `.L0 ':
readr.c:(.text._read_r+0x14): undefined reference to `_read'
e:/program files/eclipse/xpack/risc-v embedded gcc/8.2.0-3.1/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/bin/ld.exe: e:/program files/eclipse/xpack/risc-v embedded gcc/8.2.0-3.1/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/lib/rv32imac/ilp32\libg.a(lib_a-fstatr.o): in function `.L0 ':
fstatr.c:(.text._fstat_r+0x12): undefined reference to `_fstat'
e:/program files/eclipse/xpack/risc-v embedded gcc/8.2.0-3.1/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/bin/ld.exe: e:/program files/eclipse/xpack/risc-v embedded gcc/8.2.0-3.1/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/lib/rv32imac/ilp32\libg.a(lib_a-isattyr.o): in function `.L0 ':
isattyr.c:(.text._isatty_r+0xe): undefined reference to `_isatty'
collect2.exe: error: ld returned 1 exit status
make: *** [makefile:44: hello.elf] Error 1
"make all" terminated with exit code 2. Build might be incomplete.

16:36:18 Build Failed. 9 errors, 0 warnings. (took 126ms)

**Comment by ilg-ul** [comment]
What makes you think that this is an issue related to the toolchain and not an issue with your project?

For support and questions please use the project forum.

**Comment by ghost** [comment]
Hi. @puxiancheng. I am getting same error. How did you solve the issue?

**Comment by ilg-ul** [comment]
How about reading the newlib documentation? (hint: `--specs=nosys.specs`)

**Comment by ghost** [comment]
Could you elaborate "newlib documentation"? I am a newby user of eclipse embedded cdt with xpack. And I can not build a hello project although I specify xpack/bin path for compiler. What would be your detailed suggeston  for this? Thanks

**Comment by TommyMurphyTM1234** [comment]
Newlib docs are on the newlib home page.

https://sourceware.org/newlib/

**Comment by ghost** [comment]
how can i use it on eclipse?

**Comment by ilg-ul** [comment]
> how can i use it on eclipse?

Exactly the same as when you use it outside Eclipse.

When you call `printf()` in a program intended to run on a microcontroller, where do you expect the output to go?
