### ISSUE TITLE
Failed to build 9.2 RISC-V GCC

### ISSUE THREAD

**Issue by fanghuaqi** [xpack-dev-tools/riscv-none-embed-gcc-xpack#6]
### Description

I modified based on your great scripts to build riscv baremetal gcc, my gcc version used is 9.2.0, and I am able to build linux-64 and win32-x64 version, but not able to build win32 and lin32 version.

Here are the error message I got:

~~~
m 0x10000 to 0x7fff
"terminfo.tmp", line 4819, col 36, terminal 'xterm+256setaf': limiting value of `pairs' from 0x10000 to 0x7fff
"terminfo.tmp", line 4863, col 25, terminal 'xterm+direct2': limiting value of `colors' from 0x1000000 to 0x7fff
"terminfo.tmp", line 4863, col 40, terminal 'xterm+direct2': limiting value of `pairs' from 0x10000 to 0x7fff
"terminfo.tmp", line 4878, col 25, terminal 'xterm+direct': limiting value of `colors' from 0x1000000 to 0x7fff
"terminfo.tmp", line 4878, col 40, terminal 'xterm+direct': limiting value of `pairs' from 0x10000 to 0x7fff
"terminfo.tmp", line 4900, col 25, terminal 'xterm+indirect': limiting value of `colors' from 0x1000000 to 0x7fff
"terminfo.tmp", line 4900, col 40, terminal 'xterm+indirect': limiting value of `pairs' from 0x10000 to 0x7fff
"terminfo.tmp", line 7641, col 36, terminal 'dvtm-256color': limiting value of `pairs' from 0x10000 to 0x7fff
"terminfo.tmp", line 23621, terminal 'v3220': /home/hqfang/.terminfo: permission denied (errno 13)
? tic could not build /etc/terminfo:/lib/terminfo:/usr/share/terminfo
make[1]: *** [Makefile:93: install.data] Error 1
make[1]: Leaving directory '/tmp/linux-x32/build/libs/ncurses-6.2/misc'
make: *** [Makefile:124: install] Error 2
~~~

I am using the same container your shared, only modified scripts related to gcc versions, and source locations.

Thanks
Huaqi

**Comment by ilg-ul** [comment]
The error occurs while building ncurses. Your changes probably affect this too.

Try to run the build with the initial script, which should pass, and then, in a separate folder, with your changes, to see the differences.

Use `--develop` to preserve the build folders , and `--disable-multilib`, to save a lot of time.

But please be aware that you're on thin ice, the official RISC-V embedded GCC is still 8.3.

**Comment by fanghuaqi** [comment]
OK, thanks for your information, maybe I can push my changes to my repo later, ask you to review my changes if possible.

And I see the `--env-file` option, but it is not documented, I thought it is used to pass environment variable to docker, is it correct?

**Comment by TommyMurphyTM1234** [comment]
For what it's worth I did build of the 32 bit Windows and Linux toolchains earlier with the unmodified scripts and it worked fine so, as already mentioned, your changes must've broken something

Docker's --env-file option is described here:

https://docs.docker.com/engine/reference/commandline/run/

**Comment by fanghuaqi** [comment]
Yeah， @TommyMurphyTM1234 it works for me for unmodified scripts for 8.3.0-1.2 version, yeah, maybe I touched something bad, I will check.
