### ISSUE TITLE
Small enhancement: clarify prerequisites for build process

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [xpack-dev-tools/riscv-none-embed-gcc-xpack#7]
Might be helpful to clarify the following requirements in the build instructions page:

https://github.com/xpack-dev-tools/riscv-none-embed-gcc-xpack/blob/xpack/README-BUILD.md 

1. curl may need to be installed first to run the curl commands mentioned (e.g. sudo apt install curl)
2. Docker obviously needs to be installed: https://docs.docker.com/get-docker/
3. And ideally the non root user running the build added to the docker group (e.g. sudo adduser user docker and then reboot)

Same presumably goes for the Arm toolchain page?

https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/blob/xpack/README-BUILD.md

**Comment by ilg-ul** [comment]
Ah, right, the prerequisites are completely missing. :-(

Since they are the same for all builds using XBB, how about adding a single page in the XBB web and links to it in all projects?

**Comment by TommyMurphyTM1234** [comment]
That would make sense alright.
The good thing is that the prerequisites are a lot simpler now than in the past.
If you want me to draft a suggested page let me know.
Thanks

**Comment by ilg-ul** [comment]
> If you want me to draft a suggested page let me know.

definitely :-)

**Comment by TommyMurphyTM1234** [comment]
Actually I think that this may suffice unless it needs any further generalisation for other Linux distros, MacOS and maybe to dissuade people from trying to use Windows? I'm assuming that the XBB stuff runs best on MacOS or Linux only?

Maybe also a note about using a "recent" Linux/MacOS release? E.g. Ubuntu 18.04/20.04  LTS etc.?

**Prerequisites**

Before running an XBB build you must

1. Install Docker by following the relevant instructions here: 

https://docs.docker.com/get-docker/

2. On Linux, add the relevant non root user account(s) to the docker group so that docker can be run under that user account without requiring root/superuser privileges:

https://docs.docker.com/engine/install/linux-postinstall/

3. Install curl if not already installed and needed for the curl commands mentioned in the build instructions - e.g. on Ubuntu and other Linux distributions that use the apt package manager:

`sudo apt install -y curl`

**Comment by ilg-ul** [comment]
> the XBB stuff runs best on MacOS or Linux only?

the XBB stuff runs best on Linux; Docker on macOS is a bit slower due to the file system translation layer, and for complex builds, which create lots of files, I'm generally not recommending it.

**Comment by ilg-ul** [comment]
> https://docs.docker.com/get-docker/

For the install, I would use the more specific page

https://docs.docker.com/engine/install/

**Comment by TommyMurphyTM1234** [comment]
> > https://docs.docker.com/get-docker/
> 
> For the install, I would use the more specific page
> 
> https://docs.docker.com/engine/install/

That's fine by me - I was just linking the "parent" page in case they ever changed the layout below.

I'm going to sanity check the build on Ubuntu 20.04 LTS but otherwise I think that those prerequisite instructions are sufficient?

Maybe the preresuisites page should also mention the recommended or tested platforms - e.g. Ubuntu 18.04/20.04 LTS even if others should also work?

**Comment by ilg-ul** [comment]
>  I was just linking the "parent" page in case they ever changed the layout below.

yes, good point.

>  those prerequisite instructions are sufficient?

I don't know, but if they worked for you, they should be sufficient.

> the recommended or tested platforms

ah, the Travis job tests the binaries on tens of platforms (see [release](https://xpack.github.io/blog/2020/07/03/arm-none-eabi-gcc-v9-3-1-1-1-released/#travis-tests)), should we list all?

**Comment by TommyMurphyTM1234** [comment]
> I don't know, but if they worked for you, they should be sufficient.

Yes - they seem to work fine on Ubuntu 18.04 LTS and 20.04 LTS (currently still running but I don't expect problems).
I presume that things will work just as well on most or all other "recent" Linux distros.
(BTW - I'm doing a clean run of all of the builds - RISC-V nad Arm gcc toolchains, openocd and qemu just to check).

> ah, the Travis job tests the binaries on tens of platforms (see [release](https://xpack.github.io/blog/2020/07/03/arm-none-eabi-gcc-v9-3-1-1-1-released/#travis-tests)), should we list all?

OK - those tests are for the resulting tools binaries - I meant what platforms the _actual build process_ was run/tested on.

**Comment by ilg-ul** [comment]
Tommy, given the many changes in the projects, could you review this issue and the new documentation, to decide what needs to be done?

**Comment by TommyMurphyTM1234** [comment]
Yes, I can have a look at this in the next few days.

**Comment by ilg-ul** [comment]
The current XBB web page is:

- <https://xpack.github.io/xbb/>

At then end there are some links, including the prerequisites.

These pages probably need some work.

**Comment by ilg-ul** [comment]
This project is marked as DEPRECATED and is no longer maintained.

Please use the new project, riscv-none-elf-gcc-xpack.
