### ISSUE TITLE
"impossible constraint in 'asm'" error when adding single-precision hard-float 'sqrt'

### ISSUE THREAD

**Issue by bj-wanghz** [xpack-dev-tools/riscv-none-embed-gcc-xpack#8]
### Description
I want to use the single-precision hard-float `sqrt` instruction as my FPU supports `sqrt` operation. I made the following changes in Newlib (`sifive-master-xpack` branch):   
1. Create a new C file named `ef_sqrt.c` under `newlib/libm/machine/riscv` . The content of the new file is   
```
#include <math.h>

float
__ieee754_sqrtf(float x)
{
	asm ("fsqrt.s %0, %1" : "=f" (x) : "f" (x));
	return x;
} 
```
2. Modify the corresponding Makefile.am and Makefile.in under  `newlib/libm/machine/riscv` to include `ef_sqrt.c`.
3. Update the GIT_BRANCH and GIT_COMMIT for different components.

When I tried to do the building job following `README-BUILD.md`，I got the "impossible constraint in 'asm'" error at the inline assembly line  `asm ("fsqrt.s %0, %1" : "=f" (x) : "f" (x));`  in my new file. My command for building is  
```
bash ~/Downloads/riscv-none-embed-gcc-xpack.git/scripts/build.sh --all --use-gits
```
`--use-gits` option is used.

**Comment by ilg-ul** [comment]
I'm afraid I can't help you with details on the RISC-V assembler.

Please ask this in the RISC-V support forum.

And, btw, you should have figured out the syntax in a simple test program, and only when ready move to the full toolchain build.

**Comment by bj-wanghz** [comment]
@ilg-ul Okay. Thank you for your advice.
